/* Bigpipe - version 2.6
   Kenny F. 2013
*/
var BigPipe=function(g){function m(a,f){function e(){console.log("Injected content for pagelet "+a.id);f.innerHTML=a.content}function b(a,b){a=a||[];for(var d=a.length;d--;)if(a[d]===b)return!1;return!0}var h=0,d=[];return{loadCss:function(){if(a.css&&0!==a.css.length){console.log("Loading CSS for pagelet "+a.id);for(var c=h=a.css.length;c--;)b(d,a.css[c])&&(l.loadCss(a.css[c],f,function(){!--h&&e()}),d.push(a.css[c]))}else e()}}}var k=[],l=function(){function a(){if(!e){var a=navigator.userAgent.toLowerCase();
e=(/(chrome)[ \/]([\w.]+)/.exec(a)||/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version|)[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||0>a.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+)|)/.exec(a)||[])[1]}return e}var f=g.getElementsByTagName("head")[0]||g.getElementsByTagName("body")[0],e;return{loadJs:function(b,e){if("string"==typeof b||"css"==b.split(".").pop())b=b||"";if(""!==b){var d=g.createElement("script"),c=document.scripts[0];loaded=!1;d.async=!0;d.type="text/javascript";"opera"==
a()&&this.readyState&&"complete"!=this.readyState||(d.onload=function(){loaded||(console.log("loaded "+b),loaded=!0,e&&e())},d.onreadystatechange=function(){loaded||this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState||(d.onerror=d.onload=d.onreadystatechange=null,console.log("loaded "+b),loaded=!0,f&&d.parentNode&&f.removeChild(d))},c.parentNode.insertBefore(d,c),d.src=b)}},loadCss:function(b,e,d){if("string"==typeof b||"css"==b.split(".").pop())b=b||"";if(""!==b){var c=g.createElement("link");
c.rel="stylesheet";c.type="text/css";c.href=b;"msie"==a()?c.onreadystatechange=function(){/loaded|complete/.test(c.readyState)&&d()}:"opera"==a()?c.onload=d:function(){try{c.sheet.cssRule}catch(a){setTimeout(arguments.callee,20);return}d()}();f.appendChild(c);e.style.display="block"}}}}();return{OnPageLoad:function(a){if(a)try{if(window.console||(console={log:function(){}}),a.css){if("string"==typeof a.id&&(fragment=g.getElementById(a.id.toLowerCase())||""),""!==fragment){console.log("Hide content for pagelet "+
a.id);fragment.style.display="none";if(0<a.js.length)for(var f=a.js.length;f--;){var e=k.length;if(0<e)for(var b=e;b--;)e[b]!==a.js[f]&&k.push(a.js[f]);else k.push(a.js[f])}(new m(a,fragment)).loadCss();a.is_last&&function c(b){setTimeout(function(){console.log("Injecting JS file - "+a.js[b-1]);l.loadJs(a.js[b-1]);--b&&c(b)},10)}(k.length)}}else window.location.href=a.onError}catch(h){window.location.href=a.onError}}}}(document);DomReady(window,BigPipe);
function DomReady(g,m){var k=!1,l=!0,a=g.document,f=a.documentElement,e=a.addEventListener?"addEventListener":"attachEvent",b=a.addEventListener?"removeEventListener":"detachEvent",h=a.addEventListener?"":"on",d=function(c){if("readystatechange"!=c.type||"complete"==a.readyState)("load"==c.type?g:a)[b](h+c.type,d,!1),!k&&(k=!0)&&m.call(g,c.type||c)},c=function(){try{f.doScrolPageLet("left")}catch(a){setTimeout(c,50);return}d("poll")};if("complete"==a.readyState)m.call(g,"lazy");else{if(a.createEventObject&&
f.doScroll){try{l=!g.frameElement}catch(n){}l&&c()}a[e](h+"DOMContentLoaded",d,!1);a[e](h+"readystatechange",d,!1);g[e](h+"load",d,!1)}};